In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.6'

In [4]:
import sys
sys.version

'3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]'

### Creating Array

In [5]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

- list convert to array

In [7]:
arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [11]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(12,24)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [13]:
np.arange(20,10)

array([], dtype=int64)

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [16]:
arr = np.arange(22,44)

In [17]:
np.arange()

TypeError: arange() requires stop to be specified.

In [18]:
np.arange(5,15,3)

array([ 5,  8, 11, 14])

In [19]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

- 2d array

In [21]:
arr=np.zeros((2,2),dtype=int)
print(arr)
print(type(arr))

[[0 0]
 [0 0]]
<class 'numpy.ndarray'>


- 3d array

In [22]:
arr1 = np.zeros((3,12))
print(arr1)
print(type(arr1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [23]:
arr2 = np.zeros((7,12))
print(arr2)
print(type(arr2))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [24]:
arr2 = np.zeros((7,12),dtype=int)
print(arr2)
print(type(arr2))

[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]
<class 'numpy.ndarray'>


In [25]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.ones(7, dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

In [27]:
np.twos(3,4, dtype=int)

AttributeError: module 'numpy' has no attribute 'twos'

In [28]:
rand(2,3)

NameError: name 'rand' is not defined

In [29]:
random.rand(2,3)

NameError: name 'random' is not defined

In [30]:
np.random.rand(3,2)

array([[0.54737029, 0.20894361],
       [0.09615236, 0.85008956],
       [0.0195744 , 0.4729296 ]])

In [31]:
np.random.rand(4)

array([0.35598898, 0.84132595, 0.71132643, 0.78196875])

In [32]:
np.random.rand(4)

array([0.02614022, 0.80327308, 0.55934761, 0.78906372])

In [33]:
np.random.rand(4)

array([0.87944959, 0.47108343, 0.1336215 , 0.58950032])

In [34]:
np.rand(3)

AttributeError: module 'numpy' has no attribute 'rand'

In [35]:
np.random.randint(5,23)

19

In [36]:
np.random.randint(5,23,4)

array([12, 11, 20, 16], dtype=int32)

In [37]:
np.random.randint(5,23,4,2)

TypeError: Cannot interpret '2' as a data type

In [38]:
np.random.randint(8,12,(12,12))

array([[ 8, 10, 11, 11,  8,  8,  9,  9, 11,  9,  8,  8],
       [ 8,  8,  8, 11, 10, 11, 10, 10, 10,  9,  9,  8],
       [11,  9,  8,  9,  9,  9, 10,  8, 10,  8, 10, 10],
       [ 8, 10, 11, 11, 11,  8, 10, 10,  9,  8,  8,  9],
       [ 9, 11,  9, 11, 10,  8,  9,  8, 10, 11,  8,  8],
       [ 9, 11,  9, 11, 10,  8, 10, 10, 11, 11, 10,  9],
       [ 9, 10,  8,  8,  9,  9, 10, 10, 10, 10, 10,  8],
       [ 8,  9,  9, 10, 11, 10,  9, 11, 11, 11, 10, 10],
       [10,  8,  9,  8,  8,  9,  8, 11, 11,  8,  8, 10],
       [11,  9,  9, 10, 11,  9,  8, 11,  9, 11,  8,  9],
       [11,  8,  9, 11,  8, 11, 11, 10, 11, 11,  9,  9],
       [10, 10,  9, 10, 10, 10,  8, 10,  8,  9,  8,  9]], dtype=int32)

In [39]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
np.arange(1,13).reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [42]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

- sclicing in metrix

In [43]:
b = np.random.randint(12,24,(6,4))
b

array([[18, 18, 17, 23],
       [12, 13, 23, 14],
       [15, 12, 22, 14],
       [17, 15, 20, 13],
       [12, 19, 23, 14],
       [19, 21, 17, 23]], dtype=int32)

In [44]:
type(b)

numpy.ndarray

In [45]:
b[:]

array([[18, 18, 17, 23],
       [12, 13, 23, 14],
       [15, 12, 22, 14],
       [17, 15, 20, 13],
       [12, 19, 23, 14],
       [19, 21, 17, 23]], dtype=int32)

In [47]:
type(b)

numpy.ndarray

In [48]:
b[1:3]

array([[12, 13, 23, 14],
       [15, 12, 22, 14]], dtype=int32)

In [49]:
b[1,2]

np.int32(23)

In [50]:
b

array([[18, 18, 17, 23],
       [12, 13, 23, 14],
       [15, 12, 22, 14],
       [17, 15, 20, 13],
       [12, 19, 23, 14],
       [19, 21, 17, 23]], dtype=int32)

In [51]:
b[1,-1]

np.int32(14)

In [52]:
b[2:3]

array([[15, 12, 22, 14]], dtype=int32)

In [53]:
b[0:-2]

array([[18, 18, 17, 23],
       [12, 13, 23, 14],
       [15, 12, 22, 14],
       [17, 15, 20, 13]], dtype=int32)

In [54]:
b

array([[18, 18, 17, 23],
       [12, 13, 23, 14],
       [15, 12, 22, 14],
       [17, 15, 20, 13],
       [12, 19, 23, 14],
       [19, 21, 17, 23]], dtype=int32)

In [55]:
b[0,2]

np.int32(17)

In [56]:
b[-5,-3]

np.int32(13)

In [57]:
b[-5,3]

np.int32(14)

In [58]:
b[-4,2]

np.int32(22)

- operations

In [59]:
a = np.random.randint(10,20,10)
a

array([18, 11, 11, 11, 16, 11, 10, 16, 12, 11], dtype=int32)

In [60]:
id(a)

1491952184336

In [63]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[85, 42, 61, 66, 82, 53, 12, 80, 18, 16],
       [17, 32, 62, 38, 82, 94, 13, 11, 62,  0],
       [86, 35, 58, 87, 65, 92, 13, 12, 76, 72],
       [88, 90, 86, 16, 97, 51, 19, 74, 98, 84],
       [41, 36, 73, 45, 97, 89, 61, 39, 74, 20],
       [66, 14, 25, 91, 50,  7, 76, 36, 61, 21],
       [97, 21,  6, 43, 38, 46, 97, 39, 56, 42],
       [57, 38, 34, 15, 67, 78, 80, 80,  9, 19],
       [94, 61, 48, 38, 62, 15, 44, 14, 75, 68],
       [55, 53, 16, 14, 87, 77, 91,  7, 32,  4]], dtype=int32)

In [69]:
arr =np.random.randint(0,6,(1,5))
arr

array([[5, 4, 5, 2, 4]], dtype=int32)

In [70]:
arr2

array([[85, 42, 61, 66, 82, 53, 12, 80, 18, 16],
       [17, 32, 62, 38, 82, 94, 13, 11, 62,  0],
       [86, 35, 58, 87, 65, 92, 13, 12, 76, 72],
       [88, 90, 86, 16, 97, 51, 19, 74, 98, 84],
       [41, 36, 73, 45, 97, 89, 61, 39, 74, 20],
       [66, 14, 25, 91, 50,  7, 76, 36, 61, 21],
       [97, 21,  6, 43, 38, 46, 97, 39, 56, 42],
       [57, 38, 34, 15, 67, 78, 80, 80,  9, 19],
       [94, 61, 48, 38, 62, 15, 44, 14, 75, 68],
       [55, 53, 16, 14, 87, 77, 91,  7, 32,  4]], dtype=int32)

In [71]:
arr2[::-1]

array([[55, 53, 16, 14, 87, 77, 91,  7, 32,  4],
       [94, 61, 48, 38, 62, 15, 44, 14, 75, 68],
       [57, 38, 34, 15, 67, 78, 80, 80,  9, 19],
       [97, 21,  6, 43, 38, 46, 97, 39, 56, 42],
       [66, 14, 25, 91, 50,  7, 76, 36, 61, 21],
       [41, 36, 73, 45, 97, 89, 61, 39, 74, 20],
       [88, 90, 86, 16, 97, 51, 19, 74, 98, 84],
       [86, 35, 58, 87, 65, 92, 13, 12, 76, 72],
       [17, 32, 62, 38, 82, 94, 13, 11, 62,  0],
       [85, 42, 61, 66, 82, 53, 12, 80, 18, 16]], dtype=int32)

In [72]:
arr2[::-2]

array([[55, 53, 16, 14, 87, 77, 91,  7, 32,  4],
       [57, 38, 34, 15, 67, 78, 80, 80,  9, 19],
       [66, 14, 25, 91, 50,  7, 76, 36, 61, 21],
       [88, 90, 86, 16, 97, 51, 19, 74, 98, 84],
       [17, 32, 62, 38, 82, 94, 13, 11, 62,  0]], dtype=int32)

In [73]:
arr2

array([[85, 42, 61, 66, 82, 53, 12, 80, 18, 16],
       [17, 32, 62, 38, 82, 94, 13, 11, 62,  0],
       [86, 35, 58, 87, 65, 92, 13, 12, 76, 72],
       [88, 90, 86, 16, 97, 51, 19, 74, 98, 84],
       [41, 36, 73, 45, 97, 89, 61, 39, 74, 20],
       [66, 14, 25, 91, 50,  7, 76, 36, 61, 21],
       [97, 21,  6, 43, 38, 46, 97, 39, 56, 42],
       [57, 38, 34, 15, 67, 78, 80, 80,  9, 19],
       [94, 61, 48, 38, 62, 15, 44, 14, 75, 68],
       [55, 53, 16, 14, 87, 77, 91,  7, 32,  4]], dtype=int32)

In [74]:
arr2[::-3]

array([[55, 53, 16, 14, 87, 77, 91,  7, 32,  4],
       [97, 21,  6, 43, 38, 46, 97, 39, 56, 42],
       [88, 90, 86, 16, 97, 51, 19, 74, 98, 84],
       [85, 42, 61, 66, 82, 53, 12, 80, 18, 16]], dtype=int32)

In [75]:
arr2[:-3]

array([[85, 42, 61, 66, 82, 53, 12, 80, 18, 16],
       [17, 32, 62, 38, 82, 94, 13, 11, 62,  0],
       [86, 35, 58, 87, 65, 92, 13, 12, 76, 72],
       [88, 90, 86, 16, 97, 51, 19, 74, 98, 84],
       [41, 36, 73, 45, 97, 89, 61, 39, 74, 20],
       [66, 14, 25, 91, 50,  7, 76, 36, 61, 21],
       [97, 21,  6, 43, 38, 46, 97, 39, 56, 42]], dtype=int32)

In [76]:
arr.max()

np.int32(5)

In [77]:
arr.min()

np.int32(2)

In [80]:
arr.mean()

np.float64(4.0)

In [106]:
from numpy import *
arr= array([1,2,3,4,5,6,8,9])
arr

array([1, 2, 3, 4, 5, 6, 8, 9])

In [107]:
median(arr)

np.float64(4.5)

In [108]:
arr

array([1, 2, 3, 4, 5, 6, 8, 9])

In [109]:
arr.reshape(5,1)

ValueError: cannot reshape array of size 8 into shape (5,1)

In [110]:
arr.reshape(4,2,order="C")

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 9]])

In [111]:
arr.reshape(2,4, order="c")

array([[1, 2, 3, 4],
       [5, 6, 8, 9]])

In [ ]:
arr.reshape(4,2, order="F")

array([[1, 5],
       [2, 6],
       [3, 8],
       [4, 9]])

In [115]:
arr.reshape(4,2, order="A")

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 9]])

In [117]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [118]:
row=5


In [119]:
col=4

In [120]:
row

5

In [121]:
col

4

In [122]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [123]:
mat[row,col]

np.int64(54)

In [124]:
mat[5,4]

np.int64(54)

In [125]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [126]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [127]:
col=6

In [128]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [129]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [130]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [131]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [132]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [155]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [167]:
mat[1:2,2:5]

array([[12, 13, 14]])

In [168]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [169]:
mat[2:4,3:5]


array([[23, 24],
       [33, 34]])

In [170]:
mat>55

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [171]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [172]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [173]:
mat[mat==50]

array([50])

- python programme to genrate otp

In [177]:
import random

def generate_otp(length=6):
    """Generate a numeric OTP of a specified length"""
    digits = "0123456"
    otp = "".join(random.choice(digits) for _ in range(length))
    return otp

otp_length = 6
otp = generate_otp(otp_length)
print(f"Your OTP is:{otp}")

Your OTP is:014323
