
# Complete Numpy documentation
![image.png]
(attachment:e68df9a0-28a0-46c8-b643-6e13574d3be3.png)

# 1. Array Creationfunctions

In [1]:
import numpy as np

In [3]:
# creat an array from a list
a = np.array([1,2,3,4,])
print("array a:",a)

array a: [1 2 3 4]


In [4]:
# creat an array with evenly spaced values
b = np.arange(0,10,2)     # values from 0 to 10 step 2
print("array b:",b)

array b: [0 2 4 6 8]


In [7]:
# creat an array with line space values
c = np.linspace(0,1,5)
print("array c:",c)

array c: [0.   0.25 0.5  0.75 1.  ]


In [9]:
#   creat an array filled with zeros
d = np.zeros((2,3))    #  2x3 array of zeros
print("array d:\n", d)

array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# creatan array filled with ones 
e = np.ones((3,2))  # 3x2 array of ones
print("array e:\n", e)

array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
# creat an identity matrix 
f = np.eye(4)   # 4x4array of ones
print(" identity matrix f:\n", f)

 identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Manupulation Function

In [16]:
#  rashape in array
a1 = np.array([1,2,3])
reshape =np.reshape(a1,(1,3))   # rershape into 1x3
print("reshaped array:",reshape)

reshaped array: [[1 2 3]]


In [18]:
     # flattend an array  # 
f1 = np.array([[1,2],[3,4]])    # flaten to 1d array
flattend = np.ravel(f1)
print("flattend array:",flattend)

flattend array: [1 2 3 4]


In [20]:
e1 = np.array([[1,2],[3,4]])     # transposted an array
transposed = np.transpose(e1)  # transposed the array
print("transposed array:\n",transposed)

transposed array:
 [[1 3]
 [2 4]]


In [22]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [24]:
# stack array vartically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])
print("stacked array:\n",stacked)

stacked array:
 [[1 2]
 [3 4]]


# 3. Mathematical function 


In [27]:
#  add 2 array
g = np.array([1, 2, 3, 4,])
added = np.add(g, 2)  # add 2 to each element
print("added 2 to g:",added)

added 2 to g: [3 4 5 6]


In [29]:
# square each element
squared = np.power(g, 2)  # square root of each elements
print("squared g:",squared)

squared g: [ 1  4  9 16]


In [31]:
# sqare root of each element 
sqrt_val = np.sqrt(g)     # square root of each element
print("sqrt_val g:",sqrt_val)

sqrt_val g: [1.         1.41421356 1.73205081 2.        ]


In [33]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [35]:
# dot product of 2 array
a2 = np.array([1, 2, 3,])
dot_product = np.dot(a2, g)    # dot product of a and g
print("dot product of a and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [37]:
print(a)
print(a1)

[1 2 3 4]
[1 2 3]


In [39]:
a3 = np.array([1, 2, 3])
dot_product =  np.dot(a1, 1)
print("dot product of a1 and a:",dot_product)

dot product of a1 and a: [1 2 3]


# 4. Statistical Functions

In [42]:
s = np.array([1, 2, 3, 4])
mean =np.mean(s)
print("mean of s:", mean)

mean of s: 2.5


In [44]:
# standard division of array
std_dev =  np.std(s)
print("standard division:", std_dev)

standard division: 1.118033988749895


In [46]:
# minimum elements of an array
minimum = np.min(s)
print("minimum of s:",minimum)

minimum of s: 1


In [48]:
#  maximum elements of an array
maximum = np.max(s)
print("maximum of s:",maximum)


maximum of s: 4


# 5. Linear Algebra Functions

In [51]:
# creat a matrix
matrix = np.array([[1, 2],[3, 4]])

In [53]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:",determinant)

Determinant of matrix: -2.0000000000000004


In [55]:
# invers of matrix
invers = np.linalg.inv(matrix)
print("imvers of matrix:\n",invers)

imvers of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6. Random sampling function 

In [58]:
# genrate rendom values between 0 and 1
random_vals = np.random.rand(3)
print("random values:", random_vals)

random values: [0.24156175 0.0399536  0.49596135]


In [60]:
np.random.seed(0)

In [62]:
# genrate random values between 0 and 1
random_vals = np.random .rand(3)
print("random values:",random_vals)

random values: [0.5488135  0.71518937 0.60276338]


In [64]:
rand_int = np.random.randint(0, 10,size=5) # genrate random integer between 0 and 10
print("random integers:",rand_int)

random integers: [3 7 9 3 5]


In [66]:
# set seed for repoducibillity
rand_int = np.random.randint(0, 10, size=5)
print("random integers:",rand_int)

random integers: [2 4 7 6 8]


# 7.Boolean & Logical functions


In [73]:
# check if all elaments are true
# all 
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)
print("all elaments True:", all_true)

all elaments True: False


In [79]:
# check iff all elements are true
logical_test = np.array([True, False, True])
all_true = np.all (logical_test)
print("all elamrnts True:",all_true)

all elamrnts True: False


In [81]:
# check if any elementsare true
# any
any_true = np.any(logical_test)
print("any elements true:",any_true)

any elements true: True



# 8. set operations

In [86]:
# Intersections of two array
set_a =np.array ([1, 2, 3, 4])
set_b =np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("intersected of a and b:",intersection)

intersected of a and b: [3 4]


In [90]:
#  union of two array
union = np.union1d(set_a, set_b)
print("union of a and b:",union)

union of a and b: [1 2 3 4 5 6]


#  9. Array Attribute Functions

In [95]:
# attribute  array
a = np.array ([1, 2, 3, 4,])
shape = a.shape
size = a.size
dimension = a.ndim
dtype = a.dtype

print("shape of a:", shape)
print("size of a:", size)
print(" number of dimension of a:", dimension)
print("data type of a:", dtype)


shape of a: (4,)
size of a: 4
 number of dimension of a: 1
data type of a: int32


# 10. other functions


In [98]:
# creat of new copy an array
a= np.array([1, 2, 3, 4])
copied_array = np.copy(a)
print("copy of a:", copied_array)

copy of a: [1 2 3 4]


In [102]:
# size inbytes of an array
array_size_in_bytes = a.nbytes
print("size of a in bytes:", array_size_in_bytes)

size of a in bytes: 16


In [104]:
# check two array share memory
shared = np.shares_memory(a, copied_array)
print("do a and copied_array share memory?:", shared)

do a and copied_array share memory?: False


# ============= Thank You ===================================