# Numpy crash course 

In [10]:
import numpy as np

In [12]:
np.__version__

'1.26.4'

# Creating Array 

In [15]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [17]:
type(my_list)

list

In [19]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [21]:
arr

array([0, 1, 2, 3, 4, 5])

In [25]:
type(arr)

numpy.ndarray

In [27]:
type(my_list)

list

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
np.arange(2)

array([0, 1])

In [33]:
arr

array([0, 1, 2, 3, 4, 5])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
np.arange(20,10)

array([], dtype=int32)

In [45]:
arr

array([0, 1, 2, 3, 4, 5])

In [49]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [51]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [55]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [67]:
np.arange(30,20)   # 1s targ alwase be < then 2nd ag
type(np.arange)


builtin_function_or_method

In [69]:
b = np.arange(-30,20)
b


array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [71]:
np.arange(10,10)


array([], dtype=int32)

In [73]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [75]:
np.arange

<function numpy.arange>

In [82]:
np.arange(10,30,5)       # 10 starting from 30 - end point ,  count step 5

array([10, 15, 20, 25])

In [84]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [86]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [92]:
b1 = np.zeros(2)   # parameter tuning
b1

array([0., 0.])

In [100]:
np.zeros(5,dtype=int)    # hyper parameter tuning

array([0, 0, 0, 0, 0])

In [98]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [104]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [106]:
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [110]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [114]:
np.zeros((4,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [120]:
np.zeros((2,10,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [122]:
np.zeros((5,10))   # bydefaul 1arge -- will give row & 2nd arg - columns


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [124]:
n = (5,7)
n1 = (6,8)
print(np.zeros(n))# parameter tunnin g
#print(np.zeros(n1,dtype=int)) ## hypyerparameter tunning


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [128]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [130]:
np.ones( 8,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [132]:
type(np.ones)

function

In [134]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [140]:
n

(5, 7)

In [142]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [144]:
np.ones(n1)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [146]:
n1

(6, 8)

In [150]:
np.ones((5,4),dtype=int) #bydefault - 5 rows and 4 - columns


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [154]:
from  numpy import*
arange(3)


array([0, 1, 2])

In [160]:
 range(12)
print(range(12))

range(0, 12)


In [162]:
y = range(12)
y

range(0, 12)

In [168]:
np

<module 'numpy' from 'C:\\Users\\DELL\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [172]:
from numpy import*
>>> zeros(5)

array([0., 0., 0., 0., 0.])

In [179]:
np.three((3,2))

AttributeError: module 'numpy' has no attribute 'three'

In [181]:
np.random.rand(4)

array([0.64035912, 0.90546779, 0.83609308, 0.20273504])

In [183]:
np.random.rand(10)

array([0.17875412, 0.46951156, 0.48699593, 0.98077067, 0.09459839,
       0.47011239, 0.44416814, 0.5802337 , 0.21548781, 0.52758233])

In [185]:
np.random.rand(2,5)

array([[0.62864446, 0.69221364, 0.11719914, 0.35850116, 0.4836735 ],
       [0.45766635, 0.33445571, 0.98689399, 0.79917741, 0.3464647 ]])

In [196]:

np.random.randint(2,20)    # 2nd argument is exclusive

17

In [204]:
np.random.randint(0,2)

0

In [212]:
np.random.randint(1,10,3)


array([2, 2, 1])

In [214]:
np.random.randint(5,10,3)

array([6, 5, 6])

In [216]:
np.random.randint(1,3,5)

array([2, 2, 1, 1, 2])

In [220]:
np.random.randint(1)

0

In [240]:
np.random.randint(5,9)    # get the velue 1<&>5

8

In [242]:
np.random.randint(10,21,3)

array([17, 12, 14])

In [244]:
np.random.randint(1,12,3)

array([8, 8, 1])

In [250]:
np.random.randint(10,40,(10,10))

array([[15, 10, 28, 23, 22, 26, 33, 24, 30, 26],
       [24, 19, 37, 36, 17, 26, 27, 24, 33, 10],
       [18, 18, 19, 37, 39, 13, 31, 10, 32, 24],
       [22, 27, 15, 16, 37, 23, 31, 24, 14, 20],
       [38, 35, 22, 12, 20, 15, 20, 12, 11, 16],
       [37, 37, 12, 14, 11, 16, 31, 33, 11, 33],
       [28, 27, 26, 24, 14, 12, 14, 32, 39, 10],
       [24, 15, 38, 29, 19, 28, 29, 27, 36, 26],
       [16, 28, 38, 16, 29, 22, 22, 15, 19, 38],
       [26, 26, 15, 18, 17, 29, 21, 37, 38, 25]])

In [252]:
np.random.randint(5,30,(4,7))

array([[26, 16, 14, 17, 13,  9,  7],
       [25, 22,  5, 18, 12,  5,  9],
       [27,  9, 17, 21, 17, 10, 27],
       [ 5, 17,  9, 21, 23, 11,  6]])

In [254]:
b = np.random.randint(5,30,(4,8))
b

array([[15, 22, 15, 29, 20, 10,  7, 19],
       [25, 21,  7, 28, 21, 13, 10, 19],
       [14, 14, 21, 25, 11, 13, 16, 18],
       [22, 23, 24, 13, 12, 12, 13, 28]])

In [256]:
b[:]

array([[15, 22, 15, 29, 20, 10,  7, 19],
       [25, 21,  7, 28, 21, 13, 10, 19],
       [14, 14, 21, 25, 11, 13, 16, 18],
       [22, 23, 24, 13, 12, 12, 13, 28]])

In [260]:
a = np.random.randint(1,40,(10,10))
a

array([[ 4, 34, 30, 38, 11, 34, 15, 33, 31,  7],
       [15, 32, 36, 34, 29, 28, 28, 11, 24,  8],
       [16, 18, 10, 33,  1,  4, 31,  7, 35, 22],
       [36, 31, 36,  5, 11, 35, 12,  7, 11, 36],
       [29,  6, 39, 31, 16, 22, 34, 21, 38, 29],
       [ 5,  5,  1, 22, 16, 30,  3,  3, 11, 23],
       [22,  3, 27, 14, 35, 37, 10,  8, 24,  2],
       [18,  7,  1, 13, 12, 16,  3, 32, 13, 19],
       [ 8, 26, 15, 35,  9, 37, 10, 35,  6, 21],
       [25, 16, 28,  3, 22, 16, 37, 16, 32, 37]])

In [262]:
a[:]

array([[ 4, 34, 30, 38, 11, 34, 15, 33, 31,  7],
       [15, 32, 36, 34, 29, 28, 28, 11, 24,  8],
       [16, 18, 10, 33,  1,  4, 31,  7, 35, 22],
       [36, 31, 36,  5, 11, 35, 12,  7, 11, 36],
       [29,  6, 39, 31, 16, 22, 34, 21, 38, 29],
       [ 5,  5,  1, 22, 16, 30,  3,  3, 11, 23],
       [22,  3, 27, 14, 35, 37, 10,  8, 24,  2],
       [18,  7,  1, 13, 12, 16,  3, 32, 13, 19],
       [ 8, 26, 15, 35,  9, 37, 10, 35,  6, 21],
       [25, 16, 28,  3, 22, 16, 37, 16, 32, 37]])

In [264]:
a [5,5]

30

In [266]:
a [9,9]

37

In [268]:
a[3,6]

12

In [270]:
a [2,-5]

4

In [272]:
a[2,-8]

10

In [276]:
np.random.randint(10,16,(4,4))

array([[10, 13, 14, 11],
       [13, 10, 15, 10],
       [14, 11, 11, 12],
       [12, 10, 11, 12]])

# operations 

In [281]:
a = np.random.randint(10,20,5)
a

array([19, 10, 16, 10, 15])

In [283]:
arr

array([0, 1, 2, 3, 4, 5])

In [292]:
arr2 = np.random.randint(0,100,(10,10))
arr2                

array([[40, 47, 48, 43, 29, 97, 78, 50, 30, 99],
       [12, 75, 17, 93, 74, 84, 98, 18, 90, 81],
       [22, 15, 37, 35, 32, 78, 78,  8,  7, 29],
       [27, 90, 39, 92,  9, 73, 82, 26, 24, 70],
       [10, 72, 21, 28, 43, 99,  5,  5, 99, 65],
       [54, 45, 95, 84, 45, 59, 31, 55, 18,  4],
       [86, 79, 89, 73, 31, 19, 75, 13, 31, 65],
       [54, 50,  7,  5, 82, 34,  0,  8, 27,  1],
       [ 2, 83,  2, 89, 81, 26, 59, 60,  3, 39],
       [56, 92, 26, 82, 69,  2,  2, 92, 52,  5]])

In [294]:
arr

array([0, 1, 2, 3, 4, 5])

In [296]:
arr[:4]

array([0, 1, 2, 3])

In [302]:
arr2[:]

array([[40, 47, 48, 43, 29, 97, 78, 50, 30, 99],
       [12, 75, 17, 93, 74, 84, 98, 18, 90, 81],
       [22, 15, 37, 35, 32, 78, 78,  8,  7, 29],
       [27, 90, 39, 92,  9, 73, 82, 26, 24, 70],
       [10, 72, 21, 28, 43, 99,  5,  5, 99, 65],
       [54, 45, 95, 84, 45, 59, 31, 55, 18,  4],
       [86, 79, 89, 73, 31, 19, 75, 13, 31, 65],
       [54, 50,  7,  5, 82, 34,  0,  8, 27,  1],
       [ 2, 83,  2, 89, 81, 26, 59, 60,  3, 39],
       [56, 92, 26, 82, 69,  2,  2, 92, 52,  5]])

In [308]:
arr2[0:5]

array([[40, 47, 48, 43, 29, 97, 78, 50, 30, 99],
       [12, 75, 17, 93, 74, 84, 98, 18, 90, 81],
       [22, 15, 37, 35, 32, 78, 78,  8,  7, 29],
       [27, 90, 39, 92,  9, 73, 82, 26, 24, 70],
       [10, 72, 21, 28, 43, 99,  5,  5, 99, 65]])

In [310]:
arr2

array([[40, 47, 48, 43, 29, 97, 78, 50, 30, 99],
       [12, 75, 17, 93, 74, 84, 98, 18, 90, 81],
       [22, 15, 37, 35, 32, 78, 78,  8,  7, 29],
       [27, 90, 39, 92,  9, 73, 82, 26, 24, 70],
       [10, 72, 21, 28, 43, 99,  5,  5, 99, 65],
       [54, 45, 95, 84, 45, 59, 31, 55, 18,  4],
       [86, 79, 89, 73, 31, 19, 75, 13, 31, 65],
       [54, 50,  7,  5, 82, 34,  0,  8, 27,  1],
       [ 2, 83,  2, 89, 81, 26, 59, 60,  3, 39],
       [56, 92, 26, 82, 69,  2,  2, 92, 52,  5]])

In [312]:
arr2[5,8]

18

In [314]:
arr2[0,0]

40

In [318]:
arr2[9,9]

5

In [322]:
arr2[-5,-5]

59

In [326]:
arr2[-9,-9]

75

In [328]:
arr2 [2,-7]

35

In [330]:
arr2

array([[40, 47, 48, 43, 29, 97, 78, 50, 30, 99],
       [12, 75, 17, 93, 74, 84, 98, 18, 90, 81],
       [22, 15, 37, 35, 32, 78, 78,  8,  7, 29],
       [27, 90, 39, 92,  9, 73, 82, 26, 24, 70],
       [10, 72, 21, 28, 43, 99,  5,  5, 99, 65],
       [54, 45, 95, 84, 45, 59, 31, 55, 18,  4],
       [86, 79, 89, 73, 31, 19, 75, 13, 31, 65],
       [54, 50,  7,  5, 82, 34,  0,  8, 27,  1],
       [ 2, 83,  2, 89, 81, 26, 59, 60,  3, 39],
       [56, 92, 26, 82, 69,  2,  2, 92, 52,  5]])

In [332]:
arr2[::-1]

array([[56, 92, 26, 82, 69,  2,  2, 92, 52,  5],
       [ 2, 83,  2, 89, 81, 26, 59, 60,  3, 39],
       [54, 50,  7,  5, 82, 34,  0,  8, 27,  1],
       [86, 79, 89, 73, 31, 19, 75, 13, 31, 65],
       [54, 45, 95, 84, 45, 59, 31, 55, 18,  4],
       [10, 72, 21, 28, 43, 99,  5,  5, 99, 65],
       [27, 90, 39, 92,  9, 73, 82, 26, 24, 70],
       [22, 15, 37, 35, 32, 78, 78,  8,  7, 29],
       [12, 75, 17, 93, 74, 84, 98, 18, 90, 81],
       [40, 47, 48, 43, 29, 97, 78, 50, 30, 99]])

In [334]:
arr2

array([[40, 47, 48, 43, 29, 97, 78, 50, 30, 99],
       [12, 75, 17, 93, 74, 84, 98, 18, 90, 81],
       [22, 15, 37, 35, 32, 78, 78,  8,  7, 29],
       [27, 90, 39, 92,  9, 73, 82, 26, 24, 70],
       [10, 72, 21, 28, 43, 99,  5,  5, 99, 65],
       [54, 45, 95, 84, 45, 59, 31, 55, 18,  4],
       [86, 79, 89, 73, 31, 19, 75, 13, 31, 65],
       [54, 50,  7,  5, 82, 34,  0,  8, 27,  1],
       [ 2, 83,  2, 89, 81, 26, 59, 60,  3, 39],
       [56, 92, 26, 82, 69,  2,  2, 92, 52,  5]])

In [336]:
arr2[::-2]

array([[56, 92, 26, 82, 69,  2,  2, 92, 52,  5],
       [54, 50,  7,  5, 82, 34,  0,  8, 27,  1],
       [54, 45, 95, 84, 45, 59, 31, 55, 18,  4],
       [27, 90, 39, 92,  9, 73, 82, 26, 24, 70],
       [12, 75, 17, 93, 74, 84, 98, 18, 90, 81]])

In [338]:
arr2[-2::]

array([[ 2, 83,  2, 89, 81, 26, 59, 60,  3, 39],
       [56, 92, 26, 82, 69,  2,  2, 92, 52,  5]])

In [340]:
arr2[-2:]

array([[ 2, 83,  2, 89, 81, 26, 59, 60,  3, 39],
       [56, 92, 26, 82, 69,  2,  2, 92, 52,  5]])

In [342]:
arr2

array([[40, 47, 48, 43, 29, 97, 78, 50, 30, 99],
       [12, 75, 17, 93, 74, 84, 98, 18, 90, 81],
       [22, 15, 37, 35, 32, 78, 78,  8,  7, 29],
       [27, 90, 39, 92,  9, 73, 82, 26, 24, 70],
       [10, 72, 21, 28, 43, 99,  5,  5, 99, 65],
       [54, 45, 95, 84, 45, 59, 31, 55, 18,  4],
       [86, 79, 89, 73, 31, 19, 75, 13, 31, 65],
       [54, 50,  7,  5, 82, 34,  0,  8, 27,  1],
       [ 2, 83,  2, 89, 81, 26, 59, 60,  3, 39],
       [56, 92, 26, 82, 69,  2,  2, 92, 52,  5]])

In [344]:
arr2[-2:]

array([[ 2, 83,  2, 89, 81, 26, 59, 60,  3, 39],
       [56, 92, 26, 82, 69,  2,  2, 92, 52,  5]])

In [346]:
arr2[::-4]

array([[56, 92, 26, 82, 69,  2,  2, 92, 52,  5],
       [54, 45, 95, 84, 45, 59, 31, 55, 18,  4],
       [12, 75, 17, 93, 74, 84, 98, 18, 90, 81]])

In [348]:
arr

array([0, 1, 2, 3, 4, 5])

In [350]:
arr.max()

5

In [352]:
arr.min()

0

In [356]:
arr.mean()

2.5

In [360]:
arr.mediann()

AttributeError: 'numpy.ndarray' object has no attribute 'mediann'

In [362]:
from numpy import*

In [366]:
a = array([1,2,3,4,5,])
median(a)

3.0

In [368]:
arr

array([0, 1, 2, 3, 4, 5])

In [374]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [376]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [378]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [390]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [396]:
arr.reshape(2,3,order='c')

array([[0, 1, 2],
       [3, 4, 5]])

In [402]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [400]:
arr.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [404]:
arr

array([0, 1, 2, 3, 4, 5])

In [406]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [408]:

arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [410]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [412]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [414]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [420]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [422]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [424]:
arr

array([0, 1, 2, 3, 4, 5])

In [432]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

   # Indexing

In [435]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [447]:
row = 4
col = 5

In [439]:
row

4

In [449]:
col

5

In [451]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [455]:
mat[row,col]

45

In [459]:
mat[4,5]

45

In [461]:
col = 6

In [463]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [465]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [467]:
# with slice
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [469]:
col=8

In [471]:
mat[:,col]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [473]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [475]:
row = 3

In [477]:
mat [:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [479]:
mat[:,row]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [481]:
mat[5]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [483]:
mat[5,5]

55

In [485]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [487]:
mat[8,6]

86

In [489]:
mat[-8,-4]

26

In [491]:
mat[row,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [493]:
mat[:,row]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [495]:
mat[:,col]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [497]:
mat[col,:]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [499]:
mat[row:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [501]:
mat[col:]

array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [503]:
mat[9]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [505]:
mat[:9]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [509]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [519]:
mat[0:50:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [521]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [523]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [525]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [527]:
mat[2:6,2:4]  # 1:5 --->onlly row part /// 1:3--- it it indicates only column part

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [529]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [531]:
mat[0,1]

1

In [533]:
mat[1,6]

16

In [537]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [539]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [541]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [543]:
mat[3,5]

35

In [547]:
mat[5:4,5:5]

array([], shape=(0, 0), dtype=int32)

In [549]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [551]:
mat [4:5,4:6]

array([[44, 45]])

In [553]:
mat[3:6,3:6]

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

# Masking 

In [556]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [560]:
id (mat)

2612757119120

In [562]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [564]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [566]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [568]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [570]:
mat  > 0

array([[False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [572]:
mat < 0

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [574]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [576]:
mat[mat==50]

array([50])

In [580]:
a1 = mat[mat==50]
a1

array([50])

In [584]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [586]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [590]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [594]:
a3 = mat[mat>=50]
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [598]:
a4 = mat[mat<=50]
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [600]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])